### ISSUE TITLE
Configurable Product "final_price" always set to 0

### ISSUE THREAD

**Issue by revlis-x** [DivanteLtd/magento2-vsbridge-indexer#24] opened 2019-03-19 13:08 UTC
Field "final_price" of Configurable Producs (the parent) is always exported with value "0" and therefore sorting and filtering by price is not working as intended.
In mage2vs it is set to the price of the cheapest configurable child.

**Comment by afirlejczyk** [comment] 2019-03-19 14:17
I didn't notice a problem on Magento sample data.
Price is loaded from Price indexer: "catalog_product_index_price".
Hi @revlis-x 

Did you test it on Magento sample data? If not, could you show me how do you configure your configurable product?

I will try to reproduce the error. Nevertheless, I will make an adjustment for exporting configurable products.

**Comment by revlis-x** [comment] 2019-03-19 14:48
Hi @afirlejczyk,

thanks for your effort.

I have created Configurable Products with option "Apply unique prices by attribute to each SKU", so price on configurable product is grayed out. Maybe that's the issue here? Nevertheless, price filtering/sorting should also work for these kind of products.

**Comment by afirlejczyk** [comment] 2019-03-19 19:01
field "priceInclTax" is not available in elastic -> field is added by VSF or VSF-API.
https://github.com/DivanteLtd/vue-storefront/blob/master/core/modules/catalog/helpers/tax.ts
https://github.com/DivanteLtd/vue-storefront-api/blob/master/src/lib/taxcalc.js

But it might not be set correctly, because of this issue with a price: 0.

**Comment by afirlejczyk** [comment] 2019-03-20 09:40
Fixed with the latest pull request.

**Closed by afirlejczyk** 2019-03-20 09:40 UTC
